[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python simple_hr_server.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PYTHON_VERSION = "3.11"